const tags = ["Mới", "Hot", "Vip", "Độc quyền", "Ngôn tình"];

const categories = [
  { id: 1, name: "Chuyển Sinh" },
  { id: 2, name: "Action" },
  { id: 3, name: "Adult" },
  { id: 4, name: "Adventure" },
  { id: 5, name: "Anime" },
  { id: 6, name: "Fantasy" },
  { id: 7, name: "Mystery" },
  { id: 8, name: "Sci-fi" },
  { id: 9, name: "Drama" },
  { id: 10, name: "Romance" },
];

const productsData = [
  {
    id: 0,
    name: "Vưu vật - Nhi Hỉ",
    category: "Fantasy",
    tag: "Mới",
    image: "https://cnovel.net/assets/tmp/album/81787.png?v=1737361467",
    view: 10,
    follow: 2,
    description: "Vưu Vật - Nhi Hỉ được cập nhật nhanh nhất và đầy đủ nhất tại Cmanga. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ Cmanga ra các chương mới nhất của truyện Vưu Vật - Nhi Hỉ nhé.",
    chapter: [
      {
        chapterNew: "chapter 10",
        chapterCreate: "vài giây trước"
      }
    ]
  },
  {
    id: 1,
    name: "Cuộc phiêu lưu kỳ thú",
    category: "Adventure",
    tag: "Hot",
    image: "https://cnovel.net/assets/tmp/album/78255.png?v=1733832868",
    view: 50,
    follow: 15,
    description: "Cuộc phiêu lưu kỳ thú đưa bạn đến những miền đất mới lạ, những câu chuyện kỳ diệu và đầy thử thách. Một hành trình không thể bỏ qua cho những ai yêu thích khám phá.",
  },
  {
    id: 2,
    name: "Cuộc sống mơ ước",
    category: "Romance",
    tag: "Vip",
    image: "https://cnovel.net/assets/tmp/album/81781.png?v=1737349220",
    view: 80,
    follow: 40,
    description: "Cuộc sống mơ ước kể về một mối tình đầy lãng mạn, trải qua nhiều thử thách, nhưng cuối cùng lại dẫn đến một cái kết có hậu mà ai cũng mong đợi.",
  },
  {
    id: 3,
    name: "Cuộc chiến bóng tối",
    category: "Action",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/1981.png?v=1694771507",
    view: 120,
    follow: 55,
    description: "Cuộc chiến bóng tối mang đến những trận đấu nghẹt thở, đầy kịch tính với những nhân vật mạnh mẽ và những bí ẩn chưa được giải đáp. Đừng bỏ lỡ!",
  },
  {
    id: 4,
    name: "Lòng dạ ma quái",
    category: "Horror",
    tag: "Hot",
    image: "https://cmangag.com/assets/tmp/album/39032.png?v=1698118211",
    view: 200,
    follow: 70,
    description: "Lòng dạ ma quái là một câu chuyện kinh dị, hồi hộp về những bóng ma và những tâm hồn đen tối. Hãy cùng khám phá thế giới ma quái này.",
  },
  {
    id: 5,
    name: "Vương quốc huyền bí",
    category: "Fantasy",
    tag: "Vip",
    image: "https://cmangag.com/assets/tmp/album/81783.png?v=1737353540",
    view: 150,
    follow: 60,
    description: "Vương quốc huyền bí kể về một vương quốc tuyệt đẹp, nơi tồn tại những sinh vật huyền thoại và phép thuật mạnh mẽ. Một hành trình tuyệt vời đang chờ đón bạn.",
  },
  {
    id: 6,
    name: "Độc hành trên con đường hủy diệt",
    category: "Action",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/658.png?v=1694770766",
    view: 90,
    follow: 30,
    description: "Độc hành trên con đường hủy diệt là một câu chuyện về sự trả thù và khát khao chiến thắng của một người anh hùng. Hãy chuẩn bị sẵn sàng cho những trận chiến khốc liệt.",
  },
  {
    id: 7,
    name: "Chuyện tình bất diệt",
    category: "Romance",
    tag: "Hot",
    image: "https://cmangag.com/assets/tmp/album/248.png?v=1694770601",
    view: 60,
    follow: 25,
    description: "Chuyện tình bất diệt là một câu chuyện tình yêu vượt thời gian, nơi tình cảm luôn bền vững dù có trải qua bao nhiêu khó khăn.",
  },
  {
    id: 8,
    name: "Pháp sư tối thượng",
    category: "Fantasy",
    tag: "Vip",
    image: "https://cmangag.com/assets/tmp/album/58236.png?v=1721837528",
    view: 300,
    follow: 120,
    description: "Pháp sư tối thượng kể về hành trình trở thành pháp sư mạnh mẽ nhất của nhân vật chính, vượt qua những thử thách hiểm nguy, đẩy lùi bóng tối.",
  },
  {
    id: 9,
    name: "Bí mật của hồn ma",
    category: "Horror",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/39542.png?v=1702793751",
    view: 70,
    follow: 20,
    description: "Bí mật của hồn ma là câu chuyện về những hồn ma không yên nghỉ, vương vấn mãi trên thế gian. Hãy theo dõi để khám phá những bí mật kỳ lạ.",
  },
  {
    id: 10,
    name: "Bí mật của hồn ma",
    category: "Horror",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/39542.png?v=1702793751",
    view: 70,
    follow: 20,
    description: "Bí mật của hồn ma là câu chuyện về những hồn ma không yên nghỉ, vương vấn mãi trên thế gian. Hãy theo dõi để khám phá những bí mật kỳ lạ.",
  },
  {
    id: 11,
    name: "Bí mật của hồn ma",
    category: "Horror",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/39542.png?v=1702793751",
    view: 70,
    follow: 20,
    description: "Bí mật của hồn ma là câu chuyện về những hồn ma không yên nghỉ, vương vấn mãi trên thế gian. Hãy theo dõi để khám phá những bí mật kỳ lạ.",
  },
  {
    id: 12,
    name: "Bí mật của hồn ma",
    category: "Horror",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/39542.png?v=1702793751",
    view: 70,
    follow: 20,
    description: "Bí mật của hồn ma là câu chuyện về những hồn ma không yên nghỉ, vương vấn mãi trên thế gian. Hãy theo dõi để khám phá những bí mật kỳ lạ.",
  },
  {
    id: 13,
    name: "Bí mật của hồn ma",
    category: "Horror",
    tag: "Mới",
    image: "https://cmangag.com/assets/tmp/album/39542.png?v=1702793751",
    view: 70,
    follow: 20,
    description: "Bí mật của hồn ma là câu chuyện về những hồn ma không yên nghỉ, vương vấn mãi trên thế gian. Hãy theo dõi để khám phá những bí mật kỳ lạ.",
  },
];
const productCount:number = 1545;
export { tags, categories, productsData, productCount };
